// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KLCodeExtensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidKLCodeExtensionsPackageString = "f1226fcb-2210-4431-94c6-e4f826a7ffee";
        public static Guid guidKLCodeExtensionsPackage = new Guid(guidKLCodeExtensionsPackageString);

        public const string guidKLCodeExtensionsPackageCmdSetString = "90df073e-728f-45f2-9029-8ae359da79f8";
        public static Guid guidKLCodeExtensionsPackageCmdSet = new Guid(guidKLCodeExtensionsPackageCmdSetString);

        public const string guidImagesString = "6801951d-df2e-4d54-aa09-7d190c9097ee";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int KLCodeExtensionsMenuGroup = 0x1020;
        public const int KLCodeExtensionsMenu = 0x1021;
        public const int CodeLayoutCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
    }
}